# Generated by Django 5.2 on 2026-09-23 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('issue_date', models.CharField(max_length=100)),
                ('credential_id', models.CharField(blank=True, max_length=150)),
                ('credential_url', models.URLField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['is_read', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('location', models.CharField(default='Pokhara, Nepal', max_length=150)),
                ('start_year', models.CharField(default='2021', max_length=50)),
                ('end_year', models.CharField(default='2025', max_length=50)),
                ('grade_gpa', models.CharField(blank=True, default='Completed', max_length=50)),
                ('coursework', models.TextField(blank=True, help_text='Relevant coursework: Data Structures, DBMS, Operating Systems, AI, etc.')),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['display_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('location', models.CharField(default='Kathmandu, Nepal', max_length=150)),
                ('start_date', models.CharField(help_text='e.g. September 2024', max_length=100)),
                ('end_date', models.CharField(blank=True, default='Present', help_text='e.g. Present or July 2025', max_length=100)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(help_text='Bullet points or detailed responsibilities.')),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated technologies used, e.g. Python, Django, DRF, PostgreSQL', max_length=500)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='experience/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Milan Magrati', max_length=150)),
                ('title', models.CharField(default='Python Full Stack Developer', max_length=200)),
                ('bio', models.TextField(help_text='Short introduction displayed in the hero section.')),
                ('about_text', models.TextField(help_text='Detailed narrative about your background, mindset, and experience.')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('email', models.EmailField(default='milanmagrati68@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+977 986-6041157', max_length=50)),
                ('location', models.CharField(default='Kathmandu, Nepal', max_length=150)),
                ('website', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(default='https://github.com/milanmagrati')),
                ('linkedin_url', models.URLField(default='https://linkedin.com/in/milan-magrati')),
                ('availability_status', models.CharField(default='Available for Opportunities', max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('years_of_experience', models.PositiveIntegerField(default=2)),
                ('projects_completed', models.PositiveIntegerField(default=8)),
                ('technologies_count', models.PositiveIntegerField(default=18)),
                ('code_commits', models.PositiveIntegerField(default=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Personal Profile',
                'verbose_name_plural': 'Personal Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('Full Stack', 'Full Stack'), ('Backend & APIs', 'Backend & APIs'), ('Web Systems', 'Web Systems')], default='Full Stack', max_length=50)),
                ('short_description', models.CharField(max_length=350)),
                ('detailed_description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('technologies', models.CharField(help_text='Comma-separated technologies: Django, DRF, PostgreSQL, HTML5, CSS3, JS', max_length=400)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_demo_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('completion_date', models.CharField(blank=True, max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResumeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Milan Magrati CV 2026', max_length=150)),
                ('file', models.FileField(upload_to='resumes/')),
                ('is_active', models.BooleanField(default=True, help_text="When checked, this will be the file downloaded from the 'Download CV' buttons.")),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='code', help_text='Identifier: code, api, database, layout, cpu, shield', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Milan Magrati | Python Full Stack Developer', max_length=200)),
                ('meta_description', models.TextField(default='Milan Magrati - Python Full Stack Developer specializing in Django, DRF, FastAPI, PostgreSQL, RESTful APIs, and AI-assisted development.')),
                ('meta_keywords', models.CharField(default='Milan Magrati, Python Developer, Django, DRF, FastAPI, PostgreSQL, Kathmandu, Nepal, Software Engineer', max_length=300)),
                ('enable_about', models.BooleanField(default=True)),
                ('enable_skills', models.BooleanField(default=True)),
                ('enable_experience', models.BooleanField(default=True)),
                ('enable_education', models.BooleanField(default=True)),
                ('enable_projects', models.BooleanField(default=True)),
                ('enable_services', models.BooleanField(default=True)),
                ('enable_certifications', models.BooleanField(default=True)),
                ('enable_contact', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon_name', models.CharField(default='globe', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('location', models.CharField(default='Kathmandu, Nepal', max_length=150)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='portfolio.project')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.PositiveIntegerField(default=85, help_text='Proficiency percentage from 1 to 100')),
                ('icon_class', models.CharField(blank=True, help_text='Icon identifier (e.g. python, django, postgresql, git)', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillcategory')),
            ],
            options={
                'ordering': ['category__display_order', 'display_order', 'id'],
            },
        ),
    ]
